### ISSUE TITLE
Release code about wgan with AdaptiveMix

### ISSUE THREAD

**Issue by zhihangzhang** [WentianZhang-ML/AdaptiveMix#2]
Could you mind releasing code about wgan with AdaptiveMix?

**Comment by WentianZhang-ML** [comment]
Hi, would you please give us an email address or send an email to zhangwentianml@gmail.com?

**Comment by mjz0110** [comment]
> Could you mind releasing code about wgan with AdaptiveMix?

Hi，I am learning how to combine AdaptiveMix with other GAN-based model, could you please send code about wgan with AdaptiveMix to me ? Thanks for your help!

**Comment by mjz0110** [comment]
> Hi, would you please give us an email address or send an email to [zhangwentianml@gmail.com](mailto:zhangwentianml@gmail.com)?

Hi，I am learning how to combine AdaptiveMix with other GAN-based model, could you please send  the code about wgan with AdaptiveMix to me ? Thanks for your help!
