### ISSUE TITLE
Training configuration for training GAN with adaptivemix

### ISSUE THREAD

**Issue by hse1032** [WentianZhang-ML/AdaptiveMix#3]
Thanks for your great work!

I have some questions about the configuration of your work for training GANs.
Questions are as below.

1. For Table. 5 in the published paper, does both AFHQ-cat (5K) and FFHQ (Full) are trained with 25M images?, and which configuration they are trained? (e.g. 'auto' or 'paper256' etc.)
2. Which version did you use for AFHQ? Is it AFHQ-v1 or v2?

Thanks,

**Comment by WentianZhang-ML** [comment]
Hi, thanks for your attention, and sorry for the late reply. 

1. AFHQ-cat is trained with about 5k images and FFHQ (Full) is with 70k images. We used 'paper256' in the configuration to train the model. More implementation details and experimental settings are in the [related material](https://openaccess.thecvf.com/content/CVPR2023/html/Liu_AdaptiveMix_Improving_GAN_Training_via_Feature_Space_Shrinkage_CVPR_2023_paper.html). 

2. AFHQ-V2 is used in this paper.

**Comment by hse1032** [comment]
Thanks for your reply!

For the first question, I wonder if the model is trained until the discriminator saw 25M images, which is the default setting of stylegan2.

Sorry for my confusing question.

**Comment by WentianZhang-ML** [comment]
Oh, I see. You are right. We used the default setting of stylegan2 in both cases. But actually, it is not necessary for AFHQ-cat, convergence of the model can be achieved relatively faster due to the limited size of the dataset.

**Comment by hse1032** [comment]
I understood perfectly. Thanks!
