### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by ProgrammerZhujinming** [WentianZhang-ML/AdaptiveMix#4]
Hi, I got some problems when I train the model : 

run_cat_styleganv2.sh: line 18: 4037543 Segmentation fault      (core dumped) CUDA_VISIBLE_DEVICES=1 python3 generation/train.py --outdir='generation/experiments/AdaptiveMix_cat_StyleGAN_V2' --gpus=1 --data='data/afhq.zip' --mirror=1 --cfg=paper256 --aug=noaug --adaptivemix=true --noise_std=0.05
(AdaptiveMix) root@c40f242965b5:/home/zhujinming/AdaptiveMix-main# /root/anaconda3/envs/AdaptiveMix/lib/python3.8/multiprocessing/resource_tracker.py:203: UserWarning: resource_tracker: There appear to be 34 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %

Can you help me? Thanks for your reply!

**Comment by WentianZhang-ML** [comment]
Hi, happy new year! 
How many gpus do you have? If there is only one gpu, you should set CUDA_VISIBLE_DEVICES as 0. 
Otherwise, you can reduce the num_workers when you load the dataset.

**Comment by ProgrammerZhujinming** [comment]
Thanks for your reply and happy new year! Actually, I have two gpus and I set CUDA_VISIBLE_DEVICES as 1. However, I didn't notice the setting of num_workers. I will try to run again.
